accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
 # urls.py

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

        
]

kadaiapp/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from .views import CreatePost
from .views import  BlogPostSuccessView
from .views import post_detail


# URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'kadaiapp'

# URLパターンを登録するためのリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのIndexVieを実行
    # URLパターン名は'index'
    path('', views.IndexView.as_view(), name='index'),

    path(
        'blog-detail/<int:pk>/',
        views.BlogDetail.as_view(),
        name = 'blog_detail'
    ),

    path('post/', views.CreatePost.as_view(), name='post'), 

    path('post_suc/', views.BlogPostSuccessView.as_view(), name='post_suc'),

    
    path(
        'G1-list/',
        views.G1View.as_view(),
        name = 'G1_list'
    ),

    path(
        'G2-list/',
        views.G2View.as_view(),
        name = 'G2_list'
    ),

    path(
        'G3-list/',
        views.G3View.as_view(),
        name = 'G3_list'
    ),

      path(
        'user-list/',
        views.UserView.as_view(),
        name = 'user_list'
    ),

    path('mypage/', views.MypageView.as_view(), name = 'mypage'),


    path(
        'contact/',
        views.ContactView.as_view(),
        name = 'contact'
    ),


    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('post_detail/<int:pk>/', post_detail, name='post_detail'),
    # 他のURLパターン    
]

kadaiseisaku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kadaiapp.urls', namespace='kadaiapp')),
    path('', include('accounts.urls', namespace='accounts')),
    # 他のパスや名前空間があればここに追加
]

accounts/models.py
from django.db import models
# AbstractUserクラスをインポート
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    '''
    Userモデルを継承したカスタムユーザーモデル
    '''
    pass

accounts/forms.py
# UserCreationFormクラスをインポート
from django.contrib.auth.forms import UserCreationForm
# models.pyで定義したカスタムUserモデルをインポート
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    '''UserCreationFormのサブクラス
    '''
    class Meta:
        '''UserCreationFormのインナークラス
        
        Attributes:
          model:連携するUserモデル
          fields:フォームで使用するフィールド
        '''
        # 連携するUserモデルを設定
        model = CustomUser
        # フォームで使用するフィールドを設定
        # ユーザー名、メールアドレス、パスワード、パスワード(確認用)
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    '''サインアップページのビュー
    
    '''
    # forms.pyで定義したフォームのクラス
    form_class = CustomUserCreationForm
    # レンダリングするテンプレート
    template_name = "signup.html"
    # サインアップ完了後のリダイレクト先のURLパターン
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録を行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているCustomUserCreationFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    '''サインアップ成功ページのビュー
    
    '''
    # レンダリングするテンプレート
    template_name = "signup_success.html"

accounts/templates/base2.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<!-- 言語指定をjaに設定 -->
<html lang="ja">
    <head>
        
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
              
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- ページタイトル -->
        <title>{% block title %}{% endblock %}</title>
        <!-- ページタイトル横に表示されるアイコン -->
        <!-- staticでfavicon.icoのURLを生成する -->
        <link rel="icon" type="image/x-icon"
  　　　　       href={% static 'assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
                crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
              rel="stylesheet"
              type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
              rel="stylesheet"
              type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- staticでstyles.cssのURLを生成する -->
        <link href={% static 'css/styles.css' %}
              rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light"
             id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- 
                ナビゲーションバー左上のアンカーテキストとhref属性の値を設定
                -->
                <a class="navbar-brand"
                   href={% url 'kadaiapp:index' %}>Horce Race News</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse"
                     id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニュー「HOME」のhrefの値を設定
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                                href="{% url 'kadaiapp:G1_list' %}">G1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:G2_list' %}">G2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:G3_list' %}">G3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:user_list' %}">User's</a>
                        </li>
                        <li class = "nav-item">
                            <a class = "nav-link px-lg-3 py-3 py-lg-4" href = "{% url 'kadaiapp:contact' %}">CONTACT</a>
                        </li>
                         
                        {% if user.is_authenticated %}
                        <!-- ログイン中のメニュー-->
                        <li class="nav-item"><a href="{% url 'kadaiapp:mypage' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">my page</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">logout</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:password_reset' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">pass reset</a></li>
                        <li class="nav-item"><a href="mailto:admin@example.com"
                               class="nav-link px-lg-3 py-3 py-lg-4">Email</a></li>
                        {% else %}
                        <!-- ログイン状態ではない場合のメニュー-->
                        <li class="nav-item"><a href="{% url 'accounts:signup' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">signup</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:login' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">login</a></li>
                        <li class="nav-item"><a href="mailto:admin@example.com"
                               class="nav-link px-lg-3 py-3 py-lg-4">Email</a></li>
                        {% endif %}
                    </ul>
                </div>
                
            </div>
            
        </nav>
        <!-- Page Header-->
        <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <!-- Twitterのhref属性にURLを設定 -->
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  Facebookのhref属性にURLを設定 -->
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse">
                                        </i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  GitHubのhref属性にURLを設定 -->
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <!-- 著作権の記載を独自のものに変更 -->
                        <div class="small text-center text-muted fst-italic">
                            Copyright &copy; Kamada 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js">
        </script>
        <!-- Core theme JS-->
        <!-- staticでjs/scripts.jsのURLを生成する -->
        <script src={% static 'js/scripts.js' %}>
        </script>
    </body>
</html>

accounts/templates/login.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- タイトル変更 -->
    <title>Log in</title>

    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />

    <!-- Bootstrap core CSS -->
    <!--
    Bootstrap core CSSを読み込むコードをBootstrapからコピーして
    <link>タグを書き換え -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <!-- 「static/css/signin.css」の読み込み -->
    <link href={% static "css/signin.css" %}
          rel="stylesheet">
  </head>
  <body class="text-center">    
    <main class="form-signin">
      <!-- ユーザー名とパスワードが一致しない場合のメッセージ -->
      {% if form.errors %}
        <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <!-- ログインのフォームを配置 -->
      <form method="post">
        {% csrf_token %}
        <!-- Bootstrapのロゴを表示 -->
        <!-- 「static/img/bootstrap-logo.svg」の読み込み -->
        <img class="mb-4"
             src={% static "img/bootstrap-logo.svg" %}
             alt="" width="72"
             height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <!--
        <div class="form-floating">～</div>の2つのブロックを削除して
        以下に書き換え
        -->
        <!-- Usernameのラベル(非表示) -->
        <label for="Username" class="visually-hidden">
          User name</label>
        <!-- usernameの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名username -->
        <input type="text"
               name="username"
               id="id_username"
               maxlength="150"
               autocapitalize="none"
               autocomplete="username"
               class="form-control"
               placeholder="ユーザー名"
               required autofocus>
        <!-- Passwordのラベル(非表示) -->
        <label for="Password" class="visually-hidden">
          Password</label>
        <!-- passwordの<input>タグを出力-->
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
        <input type="password"
               name="password"
               id="id_password"
               autocomplete="current-password"
               class="form-control"
               placeholder="パスワード"
               required autofocus>
        
        <!-- <button>～</button>を書き換えてログインボタンを配置 -->
            <input class="w-100 btn btn-lg btn-primary"
                   type="submit"
                   value="ログイン">
        
        <!-- パスワードリセットページのリンクテキスト -->
        <br><br>
        <p><a href="{% url 'accounts:password_reset' %}">パスワードを忘れましたか?</a><p>
        <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
        <input type="hidden"
               name="next"
               value="{% url 'kadaiapp:index' %}">
      </form>
    </main>   
  </body>
</html>

accounts/templates/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base2.html' %}
{% load static %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Log out{% endblock %}

      {% block contents %}
      <header class="masthead"
        style="background-image: url({% static 'sign1.jpg' %})">
      </header>
      <!-- Bootstrapのグリッドシステム -->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">

          <h3>ログアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'kadaiapp:index' %}">トップページへ</a></p>
          </div>  
        </div>  
      </div>
      {% endblock %}
        

accounts/templates/password_reset.html
<!-- ベーステンプレートを適用する-->
{% extends 'base2.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Reset password{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の上下パディングはpy-4-->
          <div class="col py-4">
            <hr>
            <h3>パスワードをリセットしますか?</h3>
            <p>
              登録済みのメールアドレスを入力してください。
              パスワードリセットのリンクを記載したメールをすぐにお届けします。
            </p>
            <br>
            <!-- メール送信のためのフォームを配置-->
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              <!-- formに格納されているインプットボックスとラベルを出力-->
              {{form}}
              <!-- 送信ボタン -->
              <input type="submit" value="メールを受け取る" /><br>
            </form>
            <br>
            <!-- トップページへのリンク-->
            <a href="{% url 'kadaiapp:index' %}">Horce Race News</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>パスワードがリセットされました。</h2>
      <p>
        Your Password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'kadaiapp:index' %}">Horce Race Newsのトップページへ</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_form.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- マージン、パディング、背景色を設定するCSSを定義 -->
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>Horce Race News</h2>
      <h4>
        新しいパスワードを2回入力してください。これにより、
        正しく入力できたことが確認されます。
      </h4>
      <br />
      <!-- フォームを配置-->
      <form action="" method="POST">
        {% csrf_token %}
        <!-- formに格納されている要素をすべてを出力 -->
        {{form}}
        <!-- パスワードリセットボタン-->
        <input type="submit" value="パスワードリセット"/>
      </form>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
<!-- ベーステンプレートを適用する-->
{% extends 'base2.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <!-- 水平線-->
      <hr>
      <!-- Bootstrapのグリッドシステム-->
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる
               列の上下パディングはpy-4-->
          <div class="col offset-2 py-4">
              <h5>パスワードのリセット手順をメールで送信しました。
                  メールはすぐに届きます。</h5>
              <br>
              <h6>
                メールが届かない場合は、登録済みのメールアドレスであるかを
                確認し、迷惑メールフォルダーも確認してみてください。</h6>
              <br>
              <!-- トップページへのリンク-->
              <a "{% url 'kadaiapp:index' %}">Horce Race News</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup.html
<!-- ベーステンプレートを適用する -->
{% extends 'base2.html' %}
{% load static %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Sign up{% endblock %}



      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <header class="masthead"
        style="background-image: url({% static 'sign1.jpg' %})">
      </header>
      <hr>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h3>サインアップ</h3>
            <!-- サインアップのフォームを配置 -->
            <form method = "post">
              {% csrf_token %}
              <!-- formからフィールドを取り出す -->
              {% for field in form %}
               <p>
                 <!-- ラベルを出力 -->
                 {{ field.label_tag }}<br>
                 <!-- <input>タグを出力 -->
                 {{ field }}
                 <!-- help_textを出力 -->
                 {% if field.help_text %}
                   <small style="color: grey">{{ field.help_text }}</small>
                 {% endif %}
                 <!-- エラー発生時のテキストerrorsを出力 -->
                 {% for error in field.errors %}
                   <p style="color: red">{{ error }}</p>
                 {% endfor %}
               </p>
             {% endfor %}
              <p style="color:red">
                ※メールアドレスはパスワードをリセットする際に必要になりますので、
                登録をお願いします。
              </p>
              <!-- Sign upボタンを出力 -->
              <input type="submit" value="Sign up">
            </form>
            <!-- トップページのリンクテキスト -->
            <br>
            <p><a href="{% url 'kadaiapp:index' %}">
              登録をやめてトップページに戻る</a>
            </p>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base2.html' %}
{% load static %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Registration Complete{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <header class="masthead"
        style="background-image: url({% static 'sign1.jpg' %})">
      </header>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-4を入れる
               列の上下パディングはpy-4 -->
          <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <!-- ログインページのリンクテキスト -->
            <p><a href="{% url 'accounts:login' %}">ログインはこちら</a><p>
          </div>
        </div>
      </div>
      {% endblock %}