accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    

    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
 # urls.py

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

        
]

kadaiapp/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from .views import CreatePost
from .views import  BlogPostSuccessView
from .views import post_detail


# URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'kadaiapp'

# URLパターンを登録するためのリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのIndexVieを実行
    # URLパターン名は'index'
    path('', views.IndexView.as_view(), name='index'),

    path(
        'blog-detail/<int:pk>/',
        views.BlogDetail.as_view(),
        name = 'blog_detail'
    ),

    path('post/', views.CreatePost.as_view(), name='post'), 

    path('post_suc/', views.BlogPostSuccessView.as_view(), name='post_suc'),

    
    path(
        'G1-list/',
        views.G1View.as_view(),
        name = 'G1_list'
    ),

    path(
        'G2-list/',
        views.G2View.as_view(),
        name = 'G2_list'
    ),

    path(
        'G3-list/',
        views.G3View.as_view(),
        name = 'G3_list'
    ),

      path(
        'user-list/',
        views.UserView.as_view(),
        name = 'user_list'
    ),

    path('mypage/', views.MypageView.as_view(), name = 'mypage'),


    path(
        'contact/',
        views.ContactView.as_view(),
        name = 'contact'
    ),


    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('post_detail/<int:pk>/', post_detail, name='post_detail'),
    # 他のURLパターン    
]

kadaiseisaku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kadaiapp.urls', namespace='kadaiapp')),
    path('', include('accounts.urls', namespace='accounts')),
    # 他のパスや名前空間があればここに追加
]

kadaiapp/models.py
from accounts.models import CustomUser
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(verbose_name='カテゴリ', max_length=10)

    def __str__(self):
        return self.title


class BlogPost(models.Model):
    CATEGORY = (('G1','G1レースについて'),('G2','G2レースについて'),('G3','G3レースについて'),('Users','みんなのニュースについて'))
    
    title = models.CharField(verbose_name = 'タイトル',max_length = 200) #文字数
    content = models.TextField(verbose_name = '本文')
    posted_at = models.DateTimeField(verbose_name = '投稿時間',auto_now_add = True)
    category = models.CharField(verbose_name ='カテゴリ',max_length = 50,choices = CATEGORY)

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    category = models.CharField(max_length=50)
    title = models.CharField(verbose_name='タイトル', max_length=50)
    firsttext = models.TextField(verbose_name='本文', max_length=200)
    # image = models.ImageField(verbose_name='画像', upload_to='data_photo')
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)

    






    def __str__(self):
        return self.title
    

kadaiapp/forms.py
from django import forms
from .models import BlogPost
from django.forms import ModelForm


class ContactForm(forms.Form):

    name = forms.CharField(label = 'お名前')
    email = forms.EmailField(label = 'メールアドレス')
    title = forms.CharField(label = '件名')
    message = forms.CharField(label = 'メッセージ',widget=forms.Textarea)

    def __init__(self, *age, **kwargs):
        super().__init__(*age, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
        'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder'] = \
        'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = \
        'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        
        self.fields['message'].widget.attrs['placeholder'] = \
        'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        fields = ['category', 'title', 'firsttext',]

kadaiapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView,DetailView
from .models import BlogPost
from .forms import BlogPostForm
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage

from django.shortcuts import render, get_object_or_404
from .models import BlogPost




class IndexView(ListView):
    '''トップページのビュー
    
    テンプレートのレンダリングに特化したTemplateViewを継承
    
    Attributes:
      template_name: レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    context_object_name = 'orderby_records'
    queryset = BlogPost.objects.order_by('-posted_at')

    paginate_by = 4

class BlogDetail(DetailView):
    template_name = 'post.html'
    model = BlogPost

class G1View(ListView):
    template_name = 'G1_list.html'
    model = BlogPost
    context_object_name = 'G1_records'
    queryset = BlogPost.objects.filter(category = 'G1').order_by('-posted_at')
    paginate_by = 2

class G2View(ListView):
    template_name = 'G2_list.html'
    model = BlogPost
    context_object_name = 'G2_records'
    queryset = BlogPost.objects.filter(category = 'G2').order_by('-posted_at')
    paginate_by = 2
    
class G3View(ListView):
    template_name = 'G3_list.html'
    model = BlogPost
    context_object_name = 'G3_records'
    queryset = BlogPost.objects.filter(category = 'G3').order_by('-posted_at')
    paginate_by = 2

class UserView(ListView):
    template_name = 'User_list.html'
    model = BlogPost
    context_object_name = 'User_records'
    queryset = BlogPost.objects.filter(category = 'User').order_by('-posted_at')
    paginate_by = 2
    
class BlogPostSuccessView(TemplateView):
    template_name = 'post_suc.html'
    context_object_name = '-posted_at'


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('kadaiapp:contact')

    def form_valid(self,form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ:{}'.format(title)

        message = \
            '送信者名: {0}\n メールアドレス{1}\n タイトル:{2}\n メッセージ:\n{3}' \
            .format(name, email ,title, message)
        from_email = 'admin@example.com'
        to_list = ['admin@example.com']
        message = EmailMessage(subject = subject, body = message, from_email = from_email, to = to_list,)
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)
    
class MypageView(ListView):
    '''マイページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name ='mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9

    def get_queryset(self):
    
      queryset = BlogPost.objects.filter(
        user=self.request.user).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return queryset

class CreatePost(FormView):
    template_name = "post.html"
    context_object_name = '-posted_at'
    success_url = reverse_lazy('kadaiapp:post_suc')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
       context = super(CreatePost, self).get_context_data(**kwargs)
       return context
    
    def get_queryset(self):
       return BlogPost.objects.order_by('-posted_at')


class CreatePost(CreateView):
    form_class = BlogPostForm
    template_name = 'post.html'
    success_url = reverse_lazy('kadaiapp:post_suc')  # フォームが正常に送信された後のリダイレクト先URL

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.user = self.request.user
        return super().form_valid(form)
    



def post_detail(request, pk):
    post = get_object_or_404(BlogPost, pk=pk)
    return render(request, 'post_detail.html', {'post': post})

kadaiapp/templates/G1_list.html
<!-- <!DOCTYPE html> <html lang="ja">を削除-->
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Horce Race News{% endblock %}

    <!-- <head>～</head>を削除 -->
    <!-- <body>とコメントNavigatio以下の<nav>～</nav>を削除-->
        <!-- Navigation-->
        
        <!-- Page Header-->
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% block header %}
        <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグで設定-->
        <header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg1.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <!-- ヘッダーの大見出し(タイトル)を設定-->
                            <h1>Horce Race News - G1</h1>
                            <span class="subheading">
                                G1カテゴリの記事一覧
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Main Content-->
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!--
                    レコードが格納されたorderby_recordsから
                    レコードを1行ずつrecordに取り出す
                    -->
                    {% for record in G1_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <!--
                        urlでURLパターン'blog-detail/<int:pk>/'を生成し、
                        詳細ページへのリンクを設定
                        -->
                        <a href="{% url 'kadaiapp:post_detail' record.pk %}">
                            <!-- 記事のタイトル -->
                            <h2 class="post-title">
                                <!-- titleフィールドを出力-->
                                {{record.title}}</h2>
                            <!-- 投稿記事の本文 -->
                            <h3 class="post-subtitle">
                                <!-- サブタイトルの文字サイズを14ptにする-->
                                <span style="font-size : 14pt">
                                    <!--
                                    contentフィールドを出力
                                    truncatecharsで出力する文字数を50以内に制限
                                    -->
                                    {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        <!-- 投稿日時とカテゴリ-->
                        <p class="post-meta">
                            <!-- ページの最上部にリンクする-->
                            <a href="#">Horce Race News</a>
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿／カテゴリ:
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- forによる繰り返しはここまで-->
                    {% endfor %}
                      
                    <!-- Pager-->
                    <!-- ページネーションが組み込まれたテンプレートの読み込み-->
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <Footer>以下はベーステンプレートを適用するので末尾まで削除-->

kadaiapp/templates/G2_list.html
<!-- <!DOCTYPE html> <html lang="ja">を削除-->
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Horce Race News{% endblock %}

    <!-- <head>～</head>を削除 -->
    <!-- <body>とコメントNavigatio以下の<nav>～</nav>を削除-->
        <!-- Navigation-->
        
        <!-- Page Header-->
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% block header %}
        <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグで設定-->
        <header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg1.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <!-- ヘッダーの大見出し(タイトル)を設定-->
                            <h1>Horce Race News - G2</h1>
                            <span class="subheading">
                                G2カテゴリの記事一覧
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Main Content-->
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!--
                    レコードが格納されたorderby_recordsから
                    レコードを1行ずつrecordに取り出す
                    -->
                    {% for record in G2_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <!--
                        urlでURLパターン'blog-detail/<int:pk>/'を生成し、
                        詳細ページへのリンクを設定
                        -->
                        <a href="{% url 'kadaiapp:post_detail' record.pk %}">
                            <!-- 記事のタイトル -->
                            <h2 class="post-title">
                                <!-- titleフィールドを出力-->
                                {{record.title}}</h2>
                            <!-- 投稿記事の本文 -->
                            <h3 class="post-subtitle">
                                <!-- サブタイトルの文字サイズを14ptにする-->
                                <span style="font-size : 14pt">
                                    <!--
                                    contentフィールドを出力
                                    truncatecharsで出力する文字数を50以内に制限
                                    -->
                                    {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        <!-- 投稿日時とカテゴリ-->
                        <p class="post-meta">
                            <!-- ページの最上部にリンクする-->
                            <a href="#">Horce Race News</a>
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿／カテゴリ:
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- forによる繰り返しはここまで-->
                    {% endfor %}
                      
                    <!-- Pager-->
                    <!-- ページネーションが組み込まれたテンプレートの読み込み-->
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <Footer>以下はベーステンプレートを適用するので末尾まで削除-->

kadaiapp/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<!-- 言語指定をjaに設定 -->
<html lang="ja">
    <head>
        
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
              
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- ページタイトル -->
        <title>{% block title %}{% endblock %}</title>
        <!-- ページタイトル横に表示されるアイコン -->
        <!-- staticでfavicon.icoのURLを生成する -->
        <link rel="icon" type="image/x-icon"
  　　　　       href={% static 'assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
                crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
              rel="stylesheet"
              type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
              rel="stylesheet"
              type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- staticでstyles.cssのURLを生成する -->
        <link href={% static 'css/styles.css' %}
              rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light"
             id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- 
                ナビゲーションバー左上のアンカーテキストとhref属性の値を設定
                -->
                <a class="navbar-brand"
                   href={% url 'kadaiapp:index' %}>Horce Race News</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse"
                     id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニュー「HOME」のhrefの値を設定
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                                href="{% url 'kadaiapp:G1_list' %}">G1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:G2_list' %}">G2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:G3_list' %}">G3</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'kadaiapp:user_list' %}">User's</a>
                        </li>
                        <li class = "nav-item">
                            <a class = "nav-link px-lg-3 py-3 py-lg-4" href = "{% url 'kadaiapp:contact' %}">CONTACT</a>
                        </li>
                         
                        {% if user.is_authenticated %}
                        <!-- ログイン中のメニュー-->
                        <li class="nav-item"><a href="{% url 'kadaiapp:mypage' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">my page</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:logout' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">logout</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:password_reset' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">pass reset</a></li>
                        <li class="nav-item"><a href="mailto:admin@example.com"
                               class="nav-link px-lg-3 py-3 py-lg-4">Email</a></li>
                        {% else %}
                        <!-- ログイン状態ではない場合のメニュー-->
                        <li class="nav-item"><a href="{% url 'accounts:signup' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">signup</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:login' %}"
                               class="nav-link px-lg-3 py-3 py-lg-4">login</a></li>
                        <li class="nav-item"><a href="mailto:admin@example.com"
                               class="nav-link px-lg-3 py-3 py-lg-4">Email</a></li>
                        {% endif %}
                    </ul>
                </div>
                
            </div>
            
        </nav>
        <!-- Page Header-->
        <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <!-- Twitterのhref属性にURLを設定 -->
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  Facebookのhref属性にURLを設定 -->
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse">
                                        </i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  GitHubのhref属性にURLを設定 -->
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <!-- 著作権の記載を独自のものに変更 -->
                        <div class="small text-center text-muted fst-italic">
                            Copyright &copy; Kamada 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js">
        </script>
        <!-- Core theme JS-->
        <!-- staticでjs/scripts.jsのURLを生成する -->
        <script src={% static 'js/scripts.js' %}>
        </script>
    </body>
</html>

kadaiapp/templates/mypage.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
{% load static %}

<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Mypage{% endblock %}

      {% block contents %}

      <header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg1.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <!-- ヘッダーの大見出し(タイトル)を設定-->
                            <h1>Horce Race News</h1>
                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
      
      <!-- タイトルテンプレートは組み込まない-->
      
      <!-- ユーザーの投稿件数を表示-->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
          <p>投稿<strong>{{object_list.count}}</strong>件</p>
          <ul>
            {% for post in user.blogpost_set.all %}
                <li><a href="{% url 'kadaiapp:post_detail' post.id %}">{{ post.title }}</a></li>
            {% endfor %}
          </ul>
            
          {% endif %}
          <a href="{% url 'kadaiapp:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      <!-- 投稿一覧テンプレートの組み込み-->
      {% include "mypage_list.html" %}
        
      <!-- ページネーションの組み込み-->
      {% include "pagination.html" %}

      {% endblock %}

      

kadaiapp/templates/post_detail.html
<!-- post_detail.html -->

{% extends 'base.html' %}
{% load static %}

{% block contents %}
<header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg1.jpg' %})">
</header>
    <div class="container">
        
        <div>
            <div class="col-mg-8">
                <h2>{{ post.title }}</h2>
                <p>投稿者: {{ post.user.username }} | 投稿日: {{ post.posted_at|date:"F d, Y" }}</p>

                <p>{{ post.firsttext }}</p>

                <a href="{% url 'kadaiapp:post' %}" class="btn btn-primary my-3">一覧に戻る</a>
            </div>
        </div>
    </div>
{% endblock %}

kadaiapp/templates/post_suc.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Post Success{% endblock %}

    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました！</h4>
                <a href="{% url 'kadaiapp:index' %}" class="btn btn-primary my-9" type="submit">トップへ戻る</a>
            </div>
        </div>
    </div>
    {% endblock %}